### ISSUE TITLE
[Bug] Skeleton Frame is not show in Blog Page

### ISSUE THREAD

**Issue by 1chooo** [1chooo/vcard#315]
The skeleton effect is not rendering properly in the production environment. This isn't because Vercel is loading the content too quickly. I suspect the issue is related to this line:

```ts
const isLoading = !paginatedBlogs.length;
```

While the post data loads quickly, the skeleton frame seems to depend on the loading of images. We might need to use `async` logic to detect when the images are fully loaded.

@mu-irfan, do you have any other suggestions?

Related issues: #75, #314

**Comment by irfen-mi** [comment]
@1chooo Yeah, this is the situation where we use some async logic or timer functions, in this case we must need to display loader for a second to load blog images or content properly.

**Comment by 1chooo** [comment]
> @1chooo Yeah, this is the situation where we use some async logic or timer functions, in this case we must need to display loader for a second to load blog images or content properly.

Yeah, maybe we need this! I also found 

```ts
const isLoading = !paginatedBlogs.length;
```

with this logic `isLoading` is always false 👉🏻 won't call skeleton anymore!

**Comment by irfen-mi** [comment]
Alright, let me add the functional behavour of loader then.

**Comment by 1chooo** [comment]
> Alright, let me add the functional behavour of loader then.

Or maybe we could `await` for the loading the image or not?

**Comment by irfen-mi** [comment]
@1chooo i have fixed the issue, now you will be able to see the skeleton frame for blog page.

**Comment by 1chooo** [comment]
> @1chooo i have fixed the issue, now you will be able to see the skeleton frame for blog page.

Great job! Could you rebase your work onto [commit 4ddbe31](https://github.com/1chooo/1chooo.com/commit/4ddbe313dd68163788c737fd2cb06737e4338d68) and create a pull request? If possible, please include a demo video showcasing the page-switching and category-switching functionalities.

**Comment by irfen-mi** [comment]
> > @1chooo i have fixed the issue, now you will be able to see the skeleton frame for blog page.
> 
> Great job! Could you rebase your work onto [commit 4ddbe31](https://github.com/1chooo/1chooo.com/commit/4ddbe313dd68163788c737fd2cb06737e4338d68) and create a pull request? If possible, please include a demo video showcasing the page-switching and category-switching functionalities.

Rebased and code is pushed, also you can check demo video.

https://github.com/user-attachments/assets/96319395-d770-485c-b73f-6f5ca2fba52a

**Comment by 1chooo** [comment]
> > > @1chooo i have fixed the issue, now you will be able to see the skeleton frame for blog page.
> 
> > 
> 
> > Great job! Could you rebase your work onto [commit 4ddbe31](https://github.com/1chooo/1chooo.com/commit/4ddbe313dd68163788c737fd2cb06737e4338d68) and create a pull request? If possible, please include a demo video showcasing the page-switching and category-switching functionalities.
> 
> 
> 
> Rebased and code is pushed, also you can check demo video.
> 
> 
> 
> https://github.com/user-attachments/assets/96319395-d770-485c-b73f-6f5ca2fba52a
> 
> 
> 
> 

Really nice! PR please 🙏🏻

I still have another question is "could we change the logic not just for 1 second but await until fetching the images successfully"

If yes! This will be the next feature to get better experience, or in the slow internet connection, the user may face the situation that after skeleton frame loading the posts still not rendered yet.

**Comment by irfen-mi** [comment]
@1chooo no, we can't do this, we doesn't know when images and content will be load and maybe it's not fetched successfully bcz of server or api issues, this is what we can do with loaders which we already done.

**Comment by 1chooo** [comment]
> @1chooo no, we can't do this, we doesn't know when images and content will be load and maybe it's not fetched successfully bcz of server or api issues, this is what we can do with loaders which we already done.

Sure! But I cannot find the PR to get merged.
